"""Fix2

Revision ID: 015d2b3c3315
Revises: 0eea2ac198e7
Create Date: 2025-02-08 20:05:23.706399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '015d2b3c3315'
down_revision: Union[str, None] = '0eea2ac198e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.alter_column('likes', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'likes', 'comments', ['comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.alter_column('likes', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('likes', 'comment_id')
    # ### end Alembic commands ###
