"""Fix

Revision ID: 0eea2ac198e7
Revises: b1ffb9e5992a
Create Date: 2025-02-08 20:00:06.181523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eea2ac198e7'
down_revision: Union[str, None] = 'b1ffb9e5992a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
