"""new

Revision ID: f135a27a116b
Revises: 85ba29ba8968
Create Date: 2025-02-13 22:35:00.183714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f135a27a116b'
down_revision: Union[str, None] = '85ba29ba8968'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_follows_id', 'follows', type_='unique')
    op.drop_column('follows', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('follows_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.create_unique_constraint('uq_follows_id', 'follows', ['id'])
    # ### end Alembic commands ###
