services:
  db:
    image: postgres:16
    container_name: socnet_db
    env_file:
      - .env-non-dev

  redis:
    image: redis:7
    container_name: socnet_redis

  booking:
    build: 
      context: .
    container_name: socnet_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
    command: sh -c "alembic upgrade head && gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 7777:8000
  celery:
    build: 
      context: .
    container_name: socnet_celery
    command: sh -c "celery --app=app.tasks.celery_app:celery worker -l INFO"
    env_file:
      - .env-non-dev
    depends_on:
      - redis